Use TechShop
-- Cstomers who have not placed any orders.
Select Customers.CustomerID, concat(Customers.FirstName, Customers.LastName) as CustomerName
from Customers
where Customers.CustomerID Not In (Select Distinct CustomerID from Orders)

-- total number of products available for sale. 
select (select count(*) from Products) as TotalProductsAvailable

-- total revenue
Select (Select sum(TotalAmount) from Orders) as TotalRevenue

-- average quantity ordered per products in a specific category
select (select avg(Quantity) from OrderDetails where ProductID in (Select ProductID from Products where Description='Flagship Killer'))
as AverageQuantityOrdered

-- total revenue generated by a specific customer
Select (Select Sum(TotalAmount) from Orders where CustomerID=5) as TotalRevenue

-- customers who have placed the most orders
Select * from Customers Where CustomerID IN(
Select CustomerID from Orders group by CustomerID
Having Count(OrderID)=(Select Max(OrderCount) from (
	select count(OrderID) as OrderCount from Orders
	group by CustomerID) as OrderCounts ))

-- popular product category
Select Description from Products
where ProductID = (Select Top 1 ProductID from OrderDetails group by ProductID order by sum(Quantity) DESC)

--average order value
select(select sum(TotalAmount) / count(*) from Orders) as AverageOrderValue

-- total number of orders placed by each customer 
select CustomerID, concat(Customers.FirstName, Customers.LastName) as CustomerName, (Select count(*) from Orders where Orders.CustomerID=Customers.CustomerID) as OrderCount
from Customers

select * from Orders
select * from OrderDetails