Use TechShop
--orders 
Select Orders.OrderID, Orders.OrderDate, Orders.TotalAmount, Orders.Status, Customers.FirstName, Customers.LastName
From Orders
join Customers ON Orders.CustomerID=Customers.CustomerID

--total revenue generated by each electronic gadget
Select Products.ProductName, sum(Products.Price * OrderDetails.Quantity) as TotalRevenue
from OrderDetails
join Products on OrderDetails.ProductID=Products.ProductID
group by Products.ProductName

-- customers who have made at least one purchase
Select Distinct CONCAT(Customers.FirstName, Customers.LastName) as CustomerName, Customers.Email, Customers.Phone
from Customers
join Orders on Customers.CustomerID=Orders.CustomerID

-- Most popular electronic gadget
Select Top 1 Products.ProductName, sum(OrderDetails.Quantity) as TotalOrderedQuantity
from OrderDetails
join Products on OrderDetails.ProductID=Products.ProductID
Group by Products.ProductName
Order by TotalOrderedQuantity DESC

-- retrieve a list of electronic gadgets along with their corresponding categories.
Select ProductName, Description as Category
from Products
